[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_registry = "5qeuUAaJi9kTzsfmiphQ89PNrpqy7xW7sCvhBZQ6mya7"
agent_wallet_factory = "AjRqmxyieQieov2qsNefdYpa6HbPhzciED7s5TfZi1in"
compliance_registry = "7q19zbMMFCPSDhJhh3cfUVJstin6r1Q4dgmeDAuQERyK"
fee_distributor = "88eKEEMMnugv8AFWRvqa4i7LEiL7tM9bEuPTVkRbD76x"
payment_gateway = "4Qj6GziMjUfh4TszuSnasnEqnASqQBS6SHw6YAu9U23Q"

[programs.localnet]
agent_registry = "5qeuUAaJi9kTzsfmiphQ89PNrpqy7xW7sCvhBZQ6mya7"
agent_wallet_factory = "AjRqmxyieQieov2qsNefdYpa6HbPhzciED7s5TfZi1in"
compliance_registry = "7q19zbMMFCPSDhJhh3cfUVJstin6r1Q4dgmeDAuQERyK"
fee_distributor = "88eKEEMMnugv8AFWRvqa4i7LEiL7tM9bEuPTVkRbD76x"
payment_gateway = "4Qj6GziMjUfh4TszuSnasnEqnASqQBS6SHw6YAu9U23Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "pnpm exec vitest run"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
gossip_port = 18000
ledger = ".anchor/test-ledger"
rpc_port = 18899
